### ISSUE TITLE
Question: How big will the uploads to the service be?

### ISSUE THREAD

**Issue by bess** [pulibrary/openpublishing#13]
OJS has upload functionality. We are currently not customizing this or making any special accommodations for very large uploads. Do we anticipate very large uploads?

**Comment by kelynch** [comment]
After checking with the stakeholder, generally individual uploads will be small (individual PDFS), usually lower than 1GB.  Over time, there may be a need for embedded associated media files, but these could and probably should be uploaded to a media streaming platform such as Media Central, and not OJS.
