### ISSUE TITLE
Cooler URIs?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/openpublishing#24]
Any chance it's possible to remove `index.php` from the URIs? e.g. `https://ojs-dev.princeton.edu/**index.php**/jps`. Would be nice to hide that implementation detail if it can be done without a lot of fuss.

**Comment by bess** [comment]
After running the ansible playbook and cap deploy changes attached here, I believe that https://ojs-dev.princeton.edu/ is configured with restful urls as requested.

**Comment by bess** [comment]
Done! Changes applied on ojs-dev and ojs-prod and they'll get applied to ojs-staging as soon as we re-build that system with the newest ansible scripts. 

![Screen Shot 2021-04-29 at 9 12 53 AM](https://user-images.githubusercontent.com/65608/116556148-2a832f80-a8cb-11eb-8f36-d1730f348714.png)
