### ISSUE TITLE
OJS Health Science Theme Does not Work

### ISSUE THREAD

**Issue by yuanli80** [pulibrary/openpublishing#36]
Hello,

After I configured the journal website in OJS (using Health Science Theme), the journal website doesn't display in Health Science Theme. 

<img width="663" alt="Journal_Homepage_ScreenShot" src="https://user-images.githubusercontent.com/95313764/144124371-db7291f2-df92-4eed-8ddb-0bef43792fba.PNG">

Thanks,
Yuan

**Comment by yuanli80** [comment]
The Health Science theme should look like this  https://demo.publicknowledgeproject.org/ojs3/demo/index.php/health-sciences. The journal title and homepage image are customizable in the OJS (which I already did). The layout/display should be the same with the above demo site.

**Comment by kelynch** [comment]
This looks like it is a local caching issue for the reporting user's browser.  Visiting https://ojs-staging.princeton.edu/index.php/tj1 in a private tab shows the following:
<img width="1169" alt="Screen Shot 2021-12-01 at 1 26 34 PM" src="https://user-images.githubusercontent.com/7795797/144292316-8dddd0d0-8995-4a55-b3a1-799aa4abe368.png">

This is the Health Sciences theme minus the configurations in the above example.

**Comment by kelynch** [comment]
Closing this issue; the theme is configured and displaying appropriately according to the user.  There is an additional issue reported for custom header images not uploading.  I am coordinating a meeting with the stakeholder to review this and open tickets together if needed.
