### ISSUE TITLE
QuickSubmit Plugin needed in OJS

### ISSUE THREAD

**Issue by yuanli80** [pulibrary/openpublishing#37]
Please install QuickSubmit Plugin from the Plugin Gallery in OJS. Thanks!

<img width="879" alt="Plugin_Gallery" src="https://user-images.githubusercontent.com/95313764/144298863-d2f6111e-7e42-4bc8-8574-f52aa3334476.PNG">
<img width="539" alt="QuickSubmit_Plugin" src="https://user-images.githubusercontent.com/95313764/144298877-a864238e-3e7b-4222-b150-e4c7a32ac73c.PNG">

**Comment by kelynch** [comment]
Download stable version 3.3.0 here - git@github.com:pkp/quickSubmit.git

**Comment by kelynch** [comment]
Upon research, this can be installed by the admin user, in the OJS admin interface by clicking on the link highlighted in yellow above, and following the onscreen instructions.  

I suggest using this approach.  It does download the plugin onto the filesystem and extract it to `plugins/importexport/quickSubmit` as needed for the installation.  The plugin can also be uninstalled/deleted/reinstalled from this interface.
