### ISSUE TITLE
OJS- File upload permission error

### ISSUE THREAD

**Issue by yuanli80** [pulibrary/openpublishing#38]
When I made a new submission, an error occurred at the step of uploading the PDF file. 

Upload Submission page:
<img width="892" alt="Article_Submission_Page" src="https://user-images.githubusercontent.com/95313764/144635733-156067dc-7b3c-4515-b4d8-f86e5e12ce1c.PNG">

Click "Upload File" to select and upload a PDF file. Then an error occurred.
<img width="892" alt="File_Upload_Submission_Error" src="https://user-images.githubusercontent.com/95313764/144635920-d823a3cd-29af-4679-9644-4d42ab96c66f.PNG">

Acceptance Criteria:

- [x] Fix this in princeton_ansible
- [x] Run the princeton_ansible Playbook

**Comment by kelynch** [comment]
This appears to be a permissions issue on the server.  The directory should be owned by the web service user, not the deploy user.
