### ISSUE TITLE
File upload error for larger size than 1MB

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/openpublishing#40]
## Due Date

Suggested: 4/15/22 (not on fire)

Reason: This issue is not on fire for the demo stage of this project, but we would like to make sure it is addressed.

## Description

We are unable to upload files larger than 1mb. For example, (see attached image) please follow these steps:
- Select "back issues" tab
- Select one of the issues
- Go to issue gallery
- Select "create issue gallery" button
- Upload file larger than 1mb
- it returns an error messge

We tried an alternate means of uploading the file and this also returned an error. We assume the problem is with uploading a file size larger than 1mb, rather than where the upload occurs.

## Acceptance Critera

- [ ] The platform should allow file uploads larger than 1mb
- [ ] Check with Yuan or Hannah to confirm the problem is solved

![image (5)](https://user-images.githubusercontent.com/50670293/162207752-473c3f76-caa4-422c-a29d-22f107a37598.png)

**Comment by kelynch** [comment]
Depends on https://github.com/pulibrary/princeton_ansible/issues/3027
