### ISSUE TITLE
Enhance Japanese translation of OJS

### ISSUE THREAD

**Issue by kelynch** [pulibrary/openpublishing#42]
In service of OJS-based journal in Japanese, register for Weblate translation service at https://translate.pkp.sfu.ca/, set up a profile specifying "Japanese" as a chosen language that you can translate, and begin making translations.

This addresses an issue identified when working #41.

**Comment by hhkitsune** [comment]
## Translation needed:

**Announcements:** お知らせ

We were informed that there is no translation for "more" so this should be rendered in English on the page.

**Comment by kelynch** [comment]
PKP translation service seems to be experiencing a form submission bug sitewide on their end.  I've opened a thread to report and troubleshoot here - https://forum.pkp.sfu.ca/t/cannot-register-for-translation-service/74239

**Comment by kelynch** [comment]
This is apparently a known issue to do with a very recent upgrade to the platform.  It is being addressed and will be reported on here - https://forum.pkp.sfu.ca/t/cannot-login-to-weblate/74221/3

**Comment by kelynch** [comment]
Upon extensive examination, I've found the following:

* Translations are pulled from files in both the `locales` directory at the root of the application folder, and in the `lib/pkp/locales` directory.
* The "Custom Locale Editor" plugin allows any existing translation to be edited by the user, in the admin interface.  However, the files must already be present on the server, and the translation key must also already be present in one of those files in order for the user to edit it.
* Custom locale information added in the admin interface is stored in the database; there is a "restore defaults" option for locales buried in the website settings under "Hosted Journals/Settings Wizard/Journal Settings/Languages" where you expand the language in question and click "reload defaults."  See attached screenshot (because this was pretty hard to find) 
* Updated locale translations (pulling from the latest Weblate-translated versions by the community) are tracked by PKP in version control in a separate repository from OJS, https://github.com/pkp/pkp-lib.  These contain substantially more locale files than what comes with the OJS tarball typically used for installation.  The `pkp/pkp-lib` repository is tracked as a git submodule within the greater OJS project (https://github.com/pkp/ojs/blob/main/.gitmodules#L2).
* In this case, there were substantially more Japanese language translation files at https://github.com/pkp/pkp-lib/tree/main/locale/ja_JP than in the base installation.  Adding the `manager.po` file explicitly under `lib/pkp/locales/ja_JP` in the staging installation did in fact appear to address the missing translation.  This is obviously not sustainable, however it should be noted that finding a sustainable way to update the locales from `pkp-lib` is likely a reasonable approach to address this.
* For local development, it is recommended that developers clone the OJS repository and initialized submodules to get all of the latest code.  It is unclear to me what the recommended approach is for non-custom installations.

**Comment by jrgriffiniii** [comment]
This has been confirmed as completed by @carolyncole and @kelynch
