### ISSUE TITLE
Display correct Japanese font

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/openpublishing#43]
## Description

The publication *Princeton Japanese Pedagogy Forum* ([in staging](https://ojs-staging.princeton.edu/index.php/tj1)) will need to have a font applied that correctly displays Kanji characters. We were informed by a native speaker on the project that the current font isn't correct. We believe this Google font will correct the problem: [Noto Sans Japanese](https://fonts.google.com/noto/specimen/Noto+Sans+JP). The font should only be applied to Japanese language that may be displayed either through the translation feature or that may otherwise be displayed as part of the English version. Examples of Kanji used in the English version (see image) may include Japanese names next to the English names or Japanese title next to the English title.

## User Story

A user who understands Japanese language will see an interface that properly displays this language. This will show respect for Japanese culture and people, and will prevent confusion from characters that don't exactly read as expected.

## Acceptance Criteria

- [x] The font requested (or an equivalent choice, if needed) will be applied.
- [x] Japanese characters will be displayed correctly in both Japanese and English versions.
- [x] The English in the English version will still display normally.
- [x] Please reach out to Hannah or Yuan if you have other thoughts for how this issue may be addressed. 

## Supplementary

- Image is showing the English version. 
- Some Japanese should display in the English version. 
- In this image, the Japanese version of the names are shown next to the English version. Similarly the title in Japanese is next to the title in English.
- The font for Japanese needs to be changed to a font that is correct for this language, but the font used for the English is fine for English.

![Screen Shot 2022-05-26 at 4 32 59 PM](https://user-images.githubusercontent.com/50670293/170577201-f90f1d45-0e97-4b5f-b393-6658db62f4a7.jpeg)

**Comment by kelynch** [comment]
Feedback from the PO so far:

> Thanks so much! It looks like the Japanese font is where it is expected in relation to the English font. I am unable to tell if the font is completely correct (I'm not fluent in Japanese), but I told [library stakeholder] who will examine this closely with [other primary stakeholder]. They will let me know if anything appears incorrect and I will keep you posted.

**Comment by hhkitsune** [comment]
@kelynch The font was confirmed as accurate with the expert for this language. I'm closing this ticket. Thanks again for your assistance!
