### ISSUE TITLE
Figure out how to manage local changes to OJS themes

### ISSUE THREAD

**Issue by bess** [pulibrary/openpublishing#49]
When we installed OJS we were told we would not need to manage changes to local themes. However, once testing began in earnest it became clear that we DO need to accommodate local theme changes, particularly translation files. The local theme has been changed and the changes are in version control, but we don't yet have a solid way to manage and deploy these.

Request from operations:
- [x] Remove everything from the openpublishing git repo except the files we're changing and a README
- [x] Update the ansible task to pull changed files from there
- [x] Make it clear in the README that OJS gets installed via ansible

**Comment by kelynch** [comment]
Kate and Bess will investigate this and put a size on it.

**Comment by kelynch** [comment]
Addressed with Ansible PR.
